# Generated by Django 4.2.7 on 2026-03-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sellerapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='home.vendor'),
        ),
    ]
