# Generated by Django 6.0.4 on 2026-04-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_user_vendor_settings_and_product_category_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_favicons/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='featured_products_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
