# Generated by Django 4.2.7 on 2026-05-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_update_notification_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveConstraint(
            model_name='attributevalue',
            name='unique_attribute_value',
        ),
        migrations.RemoveConstraint(
            model_name='categoryattribute',
            name='unique_category_attribute',
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_product_attribute',
        ),
        migrations.RenameIndex(
            model_name='attributevalue',
            new_name='home_attrib_attribu_edf7c7_idx',
            old_name='home_attrib_attribut_idx',
        ),
        migrations.RenameIndex(
            model_name='categoryattribute',
            new_name='home_catego_categor_473311_idx',
            old_name='home_catego_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='productattribute',
            new_name='home_produc_product_6ffad1_idx',
            old_name='home_product_product_idx',
        ),
        migrations.RenameIndex(
            model_name='productattribute',
            new_name='home_produc_attribu_0121c4_idx',
            old_name='home_product_attribute_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#0d9488', help_text='Color hex code for UI', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('main', 'Main Category'), ('sub', 'Subcategory'), ('production', 'Production Level')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='home_catego_parent__1204bb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='home_catego_slug_86c5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='home_catego_level_0df427_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='home_catego_is_acti_f04d86_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='home_produc_categor_cb7dec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='home_produc_vendor__75daeb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='home_produc_slug_cc0597_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='home_produc_status_52f23e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='home_produc_is_acti_37ed06_idx'),
        ),
    ]
